server:
  port: 9001
  servlet:
    context-path: /consumer

spring:
  application:
    #定义应用名称，即服务名称
    name: consumer-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/eureka

feign:
  hystrix:
    enabled: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false